# Generated by Django 3.1.4 on 2021-03-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBookFields',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
                ('DurationInNumberSeconds', models.PositiveIntegerField()),
                ('UploadedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
