# Generated by Django 3.1.4 on 2021-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobookfields',
            name='audioFile',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
